//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWTEST
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NEWTESTEntities : DbContext
    {
        public NEWTESTEntities()
            : base("name=NEWTESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_INVOICES> TBL_INVOICES { get; set; }
        public virtual DbSet<TBL_ORDERS> TBL_ORDERS { get; set; }
        public virtual DbSet<TBL_PRODUCTS> TBL_PRODUCTS { get; set; }
        public virtual DbSet<TBL_USERS> TBL_USERS { get; set; }
    }
}
