//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INVOICES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_INVOICES()
        {
            this.TBL_ORDERS = new HashSet<TBL_ORDERS>();
        }
    
        public int I_ID { get; set; }
        public int U_ID { get; set; }
        public int I_STATUT { get; set; }
    
        public virtual TBL_USERS TBL_USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ORDERS> TBL_ORDERS { get; set; }
    }
}
